import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
<<<<<<< HEAD
  title: "E-cart",
  description: "E-cart Website",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 985cc6c46b724af8f1a0c35f197163c679cb6664
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
